---
Name: innowebgoogleanalytics
---
SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - Innoweb\GoogleAnalytics\Extensions\ControllerExtension
---
Only:
  classexists: 'Symbiote\Multisites\Multisites'
---
Symbiote\Multisites\Model\Site:
  extensions:
    - Innoweb\GoogleAnalytics\Extensions\ConfigExtension
---
Except:
  classexists: 'Symbiote\Multisites\Multisites'
---
Silverstripe\SiteConfig\SiteConfig:
  extensions:
    - Innoweb\GoogleAnalytics\Extensions\ConfigExtension
